#!/usr/bin/env python3
"""
make_front_cam_extrinsics.py
============================
Write extrinsics.yaml's ``T_mb2fc_row_major`` from robot.yaml — the ONLY
way that block should ever change (2026-09-15).

T_mb2fc is the pose of the PHYSICAL front_cam optical frame in the
mobile-base frame. Its rotation embeds the ground-plane fit
(robot.yaml ``robot_camera.ground_plane.front_cam``: roll / pitch / yaw
measured 2026-09-08/09 with a laid tag pair), its tx is ``robot.camera_offset``
and its tz is the fit's ``height_m`` — three numbers that already live in
robot.yaml, so this script derives the matrix instead of anyone typing it:

    T_mb2fc_level    = [R_MB2FC_LEVEL | (camera_offset, 0, height_m)]
    T_mb2fc_physical = T_mb2fc_level @ inv(T_tilted_to_level(roll, pitch, yaw))

Consumers get the level frame back through
``path_tag_locator.constants.load_extrinsics_full`` (which also refuses a
matrix that no longer matches robot.yaml). Re-run after any camera remount
or re-fit: ``tools/fit_front_cam_ground.py`` -> robot.yaml -> this script.

Usage:
    python3 make_front_cam_extrinsics.py            # print the block + diff
    python3 make_front_cam_extrinsics.py --apply    # rewrite the block in place
"""
import argparse
import math
import os
import re
import sys

import numpy as np
import yaml

_HERE = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.join(_HERE, "..", "src"))

from apriltag_nav.ground_plane import T_tilted_to_level          # noqa: E402
from apriltag_nav.paths import CONFIG_PATH                        # noqa: E402
from path_tag_locator.constants import R_MB2FC_LEVEL              # noqa: E402
from path_tag_locator.geometry import invert_T                    # noqa: E402

DEFAULT_EXTRINSICS = os.path.join(_HERE, "..", "config", "extrinsics.yaml")


def physical_T_mb2fc(robot_cfg):
    """(T_mb2fc_physical, params dict) from a parsed robot.yaml."""
    cam_off = float(robot_cfg["robot"]["camera_offset"])
    cam_lat = float(robot_cfg["robot"].get("camera_lateral", 0.0))
    gp = ((robot_cfg.get("robot_camera") or {}).get("ground_plane") or {}).get("front_cam") or {}
    roll = float(gp.get("roll_deg", 0.0))
    pitch = float(gp.get("pitch_deg", 0.0))
    yaw = float(gp.get("yaw_deg", 0.0))
    height = float(gp.get("height_m", 0.30))
    T_level = np.eye(4)
    T_level[:3, :3] = R_MB2FC_LEVEL
    T_level[:3, 3] = [cam_off, cam_lat, height]
    tilt = T_tilted_to_level(math.radians(roll), math.radians(pitch), math.radians(yaw))
    T_phys = T_level @ invert_T(tilt)
    return T_phys, dict(camera_offset=cam_off, camera_lateral=cam_lat, roll_deg=roll,
                        pitch_deg=pitch, yaw_deg=yaw, height_m=height)


def format_block(T, params):
    rows = []
    for r in range(4):
        cells = ["%12.9f" % T[r, c] for c in range(4)]
        rows.append("   " + ", ".join(cells) + ("," if r < 3 else "]"))
    rows[0] = "  [" + rows[0][3:]
    head = ("T_mb2fc_row_major:   # GENERATED by scripts/make_front_cam_extrinsics.py "
            "from robot.yaml: camera_offset %.3f, camera_lateral %.3f, ground_plane.front_cam "
            "roll %+.3f pitch %+.3f yaw %+.3f deg, height_m %.3f — do not hand-edit\n"
            % (params["camera_offset"], params["camera_lateral"], params["roll_deg"],
               params["pitch_deg"], params["yaw_deg"], params["height_m"]))
    return head + "\n".join(rows) + "\n"


_BLOCK_RE = re.compile(r"^T_mb2fc_row_major:[^\n]*\n(?:[^\n]*\n)*?[^\n]*\]\s*\n",
                       re.MULTILINE)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--robot-yaml", default=CONFIG_PATH)
    ap.add_argument("--extrinsics", default=DEFAULT_EXTRINSICS)
    ap.add_argument("--apply", action="store_true", help="rewrite the block in place")
    args = ap.parse_args()

    with open(args.robot_yaml) as fh:
        robot_cfg = yaml.safe_load(fh)
    T, params = physical_T_mb2fc(robot_cfg)
    block = format_block(T, params)
    print(block, end="")

    with open(args.extrinsics) as fh:
        text = fh.read()
    m = _BLOCK_RE.search(text)
    if not m:
        sys.exit("T_mb2fc_row_major block not found in %s" % args.extrinsics)
    if m.group(0) == block:
        print("-- %s already up to date" % args.extrinsics)
        return
    if not args.apply:
        print("-- differs from %s (run with --apply to rewrite)" % args.extrinsics)
        return
    new_text = text[:m.start()] + block + text[m.end():]
    with open(args.extrinsics, "w") as fh:
        fh.write(new_text)
    # round-trip: the loader must accept what was written
    from path_tag_locator.constants import load_extrinsics_full
    ext = load_extrinsics_full(args.extrinsics, robot_yaml_path=args.robot_yaml)
    print("-- wrote %s; loader: %s" % (args.extrinsics, ext.note))


if __name__ == "__main__":
    main()
